services:
  minio:
    image: minio/minio:latest
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=${S3_ACCESS_KEY}
      - MINIO_SECRET_KEY=${S3_SECRET_KEY}
      - MINIO_HTTP_TRACE=/var/log/minio.log
      - MINIO_PROMETHEUS_AUTH_TYPE=public
    command: server --console-address ":9001" /data
    volumes:
      - ./data/minio/data:/data
      - ./data/minio/log:/var/log
    healthcheck:
      test: [ "CMD", "curl -I http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 80s

  rabbit:
    image: rabbitmq:4.0.2-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${MQ_PASS}
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  rabbit-unmanaged:
    image: rabbitmq:4.0.2
    restart: always
    ports:
      - "5673:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=${MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${MQ_PASS}
    volumes:
      - ./data/rabbitmq-unmanaged:/var/lib/rabbitmq


  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POETRY_VERSION=1.8.3
    ports:
      - "8080:80"
    env_file:
      - ./envs/prod.env