"""added events

Revision ID: d176f16ad800
Revises: fa87434f4bea
Create Date: 2024-10-13 19:23:17.291660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd176f16ad800'
down_revision: Union[str, None] = 'fa87434f4bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('message', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('coins', sa.Column('price', sa.Float(), nullable=True))
    op.alter_column('coins', 'price_updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_transactions_of_statistics_symbols'), 'transactions_of_statistics', ['symbols'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_of_statistics_symbols'), table_name='transactions_of_statistics')
    op.alter_column('coins', 'price_updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('coins', 'price')
    op.drop_table('events')
    # ### end Alembic commands ###
