"""empty message

Revision ID: fa87434f4bea
Revises: 
Create Date: 2024-09-30 02:33:13.636799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'fa87434f4bea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets_statistics',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('symbols', sa.String(length=10), nullable=False),
                    sa.Column('full_price', sa.Float(), nullable=False),
                    sa.Column('amount_coin', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_assets_statistics_symbols'), 'assets_statistics', ['symbols'], unique=False)
    op.create_table('coins',
                    sa.Column('symbols', sa.String(length=10), nullable=False),
                    sa.Column('price_updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('symbols')
                    )
    op.create_table('transactions',
                    sa.Column('id', sa.String(length=50), nullable=False),
                    sa.Column('symbols', sa.String(length=10), nullable=False),
                    sa.Column('direction', sa.Boolean(), nullable=False),
                    sa.Column('amount_usdt', sa.Float(), nullable=False),
                    sa.Column('amount_coin', sa.Float(), nullable=False),
                    sa.Column('dt', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('transactions_of_statistics',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('symbols', sa.String(length=10), nullable=False),
                    sa.Column('direction', sa.Boolean(), nullable=False),
                    sa.Column('amount_usdt', sa.Float(), nullable=False),
                    sa.Column('amount_coin', sa.Float(), nullable=False),
                    sa.Column('remaining_coin', sa.Float(), nullable=False),
                    sa.Column('dt', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions_of_statistics')
    op.drop_table('transactions')
    op.drop_table('coins')
    op.drop_index(op.f('ix_assets_statistics_symbols'), table_name='assets_statistics')
    op.drop_table('assets_statistics')
    # ### end Alembic commands ###
