name: Only testing

on:
  push:
    branches:
      - master


jobs:
  Test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python installation
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --with dev
      - name: Configure PYTHONPATH
        run: export PYTHONPATH="${PYTHONPATH}:/src"
      - name: Run tests
        shell: bash -l
        run: pytest tests/

